# 工作空间
workspace = "E:\\dubhe-workspace"

# 构建并发数
capacity = 2

[http]
address = ":8000"

[server]
# gRPC 监听地址
address = ":9090"
# 使用网络
network = "tcp"

[database]
# 是否开启调试模式
debug = false
# 数据库类型(目前支持的数据库类型：mysql/sqlite3)
db_type = "sqlite3"
# 数据库链接地址 mysql:  <user>:<password>@tcp(<host>:<port>)/<dbname>?<parameters> sqlite3: path
dsn = "C:\\Users\\a3139\\dubhe.db"
# 设置连接可以重用的最长时间(单位：秒)
max_lifetime = 7200
# 设置数据库的最大打开连接数
max_open_conns = 150
# 设置空闲连接池中的最大连接数
max_idle_conns = 50

[log]
# 日志级别(1:fatal 2:error,3:warn,4:info,5:debug)
level = 5
# 日志格式（支持输出格式：text/json/nested）
format = "nested"
# info日志文件输出位置
info_path = ""
# error日志文件输出位置
error_path = ""

[jwt]
# 签名key
signing_key = "gJbQry0vb02IjHQyKWlxQwZAwwZ7IC0e"
# 过期时间（单位秒）
expired = 7200

[super_user]
nickname = "Admin"
username = "admin"
password = "admin"